### ISSUE TITLE
Support for piped wiki links 

### ISSUE THREAD

**Issue by kevinslin** [kortina/vscode-markdown-notes#66] opened 2020-07-19 15:00 UTC
**Is your feature request related to a problem? Please describe.**

I use [piped wiki links](https://www.mediawiki.org/wiki/Help:Links/sco
) `[[My Title | link-to-file.md]]` for my documents. Today, when I try to navigate to a piped link, `markdown-notes` will create a new file with the pipe in the title

- eg: following this link `[[workspace|pro.dendron.topic.workspace.md]]` results in this file `workspace|pro.dendron.topic.workspace.md` being created

**Describe the solution you'd like**

Following `[[workspace|pro.dendron.topic.workspace.md]]` should result with the following file `pro.dendron.topic.workspace.md` 

**Describe alternatives you've considered**

**Additional context**

**Comment by kortina** [comment] 2020-07-19 15:51
This is a duplicate of https://github.com/kortina/vscode-markdown-notes/issues/56

Let's consolidate the conversation there.

**Closed** 2020-09-17 05:05 UTC
